### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by kazijawad** [TEDxCMU/TEDApp#29]
- [ ] Google Analytics PageView Tracking
- [ ] Google Analytics Events
- [x] Metadata Updates
- [x] Twitter Share
- [x] Facebook Share
- [ ] 301 Redirects
- [ ] QA - IE 10+
- [ ] QA - iOS
- [ ] QA - Android
- [ ] QA - Landscape Mobile
- [ ] QA - Safari
- [ ] QA - Firefox
- [ ] QA - Chrome
- [ ] QA - Slower Connection
- [ ] Light ADA Pass
- [x] Favicon
- [ ] Correct Legal Links
- [ ] Performance Check
- [ ] Media Optimization
- [x] Old App Backup
- [ ] Handle 404 Errors (prerender-status-code tag)
- [ ] Test Form Functionality
- [ ] Form Validation
- [ ] Fix Console Errors
- [ ] Ensure Correct Social Links
- [x] WWW Issues
- [x] HTTPS Issues
- [ ] Cover Host Performance Settings
- [ ] Google Webmaster Indexing
- [ ] Google Webmaster Sitemap
- [ ] Correct Fonts
- [ ] https://web.dev/measure
- [ ] https://frontendchecklist.io/
